# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yaml and/or the recipe/meta.yaml.

language: objective-c

env:
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "BBzn+LsQZgYLrV5rxKkdhas8uwpXSKQXZigRugjdWsWNwIVvzE8lceLZvnb5QnXx3C7RfSUDMnUsBF6K9GU5zknpS+A0wNEyfaTUQkSYGLWcE/zY3cFxeoTa592J424J35s3139W1dYBKwr9FBKp36Gc2E2MaWX0o6hk5EIDhi1yQjSbP5kLr6cJAtx61J1ZDbXymIwXhcbRILIu4Jo+zwwhey/yezVfbahDkXnNJEeUq1MRM1tWzs5hMH63myK/X4NBnkGlUi4CL83YI9elFKhCfzsGhssmjtrp9BCcOdGQRqfm85ZETX24qP2HlsRj9+90rxSnFh4FAy5CyJmqX/7VwKAyPSwbmb0KvKRo0JcSVsdyX3QwD/hqd1WNobbyWKoOn/EjomJXgtevgJbPOWnAcwn1GEMJlX1JsuIG7JqR50jI/bQl7CPEeXKnZTDUsy6EW6fJApWivVFBP/y/S8K2CEEJ4tJtjWwTTu0/RdThL9RmgeZjrEXCq4xc4JcEp/iK9ZhGtjLdpcExtyzPcqpoH/MHJ2q4FbouIlU1wouBalLdMr3e5QtEdbUyuuwwPK86kpQfzMF3ZcYVFvdt5fHkPbpYuVmbj7DDEzowNvQarB05WLBIgk7WAb5v2HZqFgieOCWaA/Axzl4cwPm1+GAuhl1FZf/O9muoEsevJYo="


before_install:
    # Remove homebrew.
    - brew remove --force $(brew list)
    - brew cleanup -s
    - rm -rf $(brew --cache)

install:
    - |
      MINICONDA_URL="http://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

      export PATH=/Users/travis/miniconda3/bin:$PATH

      conda config --set show_channel_urls true
      conda update --yes conda
      conda install --yes conda-build=1.20.0 jinja2 anaconda-client
      conda config --add channels conda-forge
      

script:
  - conda build ./recipe

after_success:

  - ./ci_support/upload_or_check_non_existence.py ./recipe conda-forge --channel=main
