travis:
  secure:
    BINSTAR_TOKEN: BBzn+LsQZgYLrV5rxKkdhas8uwpXSKQXZigRugjdWsWNwIVvzE8lceLZvnb5QnXx3C7RfSUDMnUsBF6K9GU5zknpS+A0wNEyfaTUQkSYGLWcE/zY3cFxeoTa592J424J35s3139W1dYBKwr9FBKp36Gc2E2MaWX0o6hk5EIDhi1yQjSbP5kLr6cJAtx61J1ZDbXymIwXhcbRILIu4Jo+zwwhey/yezVfbahDkXnNJEeUq1MRM1tWzs5hMH63myK/X4NBnkGlUi4CL83YI9elFKhCfzsGhssmjtrp9BCcOdGQRqfm85ZETX24qP2HlsRj9+90rxSnFh4FAy5CyJmqX/7VwKAyPSwbmb0KvKRo0JcSVsdyX3QwD/hqd1WNobbyWKoOn/EjomJXgtevgJbPOWnAcwn1GEMJlX1JsuIG7JqR50jI/bQl7CPEeXKnZTDUsy6EW6fJApWivVFBP/y/S8K2CEEJ4tJtjWwTTu0/RdThL9RmgeZjrEXCq4xc4JcEp/iK9ZhGtjLdpcExtyzPcqpoH/MHJ2q4FbouIlU1wouBalLdMr3e5QtEdbUyuuwwPK86kpQfzMF3ZcYVFvdt5fHkPbpYuVmbj7DDEzowNvQarB05WLBIgk7WAb5v2HZqFgieOCWaA/Axzl4cwPm1+GAuhl1FZf/O9muoEsevJYo=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
